name: Linux Compile test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:40
    steps:
      - run: cat /etc/os-release
      - name: Install git
        run: |
          dnf install git -y
      - uses: actions/checkout@v4.1.1
        with:
          submodules: "true"
      - name: Get Complementary file
        uses: actions/checkout@v4.1.1
        with:
          path: complementary_file
          repository: UnspaghettifyKart/action-build-private-file
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install dependencies
        run: |
          dnf install gcc gcc-c++ cmake ninja-build lsb_release SDL2-devel libpng-devel libzip-devel libzip-tools json-devel tinyxml2-devel spdlog-devel boost-devel SDL2_net-devel -y
      - name: Build
        run: |
          cp -r complementary_file/* .
          echo "${{ secrets.AES_KEY }}" | openssl enc -d -aes-256-cbc -pass stdin -pbkdf2 -in baserom.us.z64.aes -out baserom.us.z64
          cmake -H. -Bbuild-cmake -GNinja
          cmake --build build-cmake --target ExtractAssets
          cmake --build build-cmake
